### ISSUE TITLE
Broken after 2022.9 update

### ISSUE THREAD

**Issue by grouts112** [michelebossa/HA-Scheduler#13]
Been using Ha scheduler for many months.. thank you.
But I updated to the latest release 2022.9 and the schedules don’t run,
And the scheduling view doesn't display at all.
 Updated to 2022.9.1 and still not working.

**Comment by grouts112** [comment]
From addon log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 0.
[12:29:28] ERROR: Got unexpected response from the API: System is not ready with state: setup
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:29:29] INFO: Start
[12:29:29] INFO: ready hassio.stdin
Traceback (most recent call last):
  File "/home/app.py", line 507, in <module>
    get_elements()
  File "/home/app.py", line 414, in get_elements
    json_data = response.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
Daemon Start
Traceback (most recent call last):
  File "/home/daemon.py", line 369, in <module>
    get_sun()
  File "/home/daemon.py", line 61, in get_sun
    json_data = response.json()["attributes"]
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by grouts112** [comment]
Performed a “Rebuild” on the addon
 And the web gui page now displays again.
Just need to see if the schedules are working again.
Possibly resolved by the rebuild. Will update again tomorrow.

**Comment by grouts112** [comment]
Rebuild resolved.
Closing.
