### ISSUE TITLE
502: Bad Gateway error on reboot

### ISSUE THREAD

**Issue by DarioB92** [michelebossa/HA-Scheduler#14]
On boot/reboot the add-on doesn't start correctly, I need to restart it manually in order to use it. Watchdog isn't triggered by this error.
How could I solve this? Thanks

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: HA Scheduler
 Home Assistant scheduler
-----------------------------------------------------------
 Add-on version: 0.17
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.11.dev1507
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:25:15] INFO: Start
[15:25:15] INFO: ready hassio.stdin
Daemon Start
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/app.py", line 507, in <module>
    get_elements()
  File "/home/app.py", line 414, in get_elements
    json_data = response.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/daemon.py", line 369, in <module>
    get_sun()
  File "/home/daemon.py", line 61, in get_sun
    json_data = response.json()["attributes"]
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by Senecar78** [comment]
I am having the same issue... 502 error, and no watchdog. However rebooting only allows the scheduler to start but does not execute the automations.
